server:
  port: 9998

spring:
  kafka:
    producer:
      bootstrap-servers: 192.168.40.131:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer